#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <xbox_legorc_bridge_icons.h>

int32_t xbox_legorc_bridge_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm xbox_legorc_bridge!");

    return 0;
}
